packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.4
  '@types/node': ^24.10.0
  '@vitest/coverage-v8': ^4.0.8
  kysely: ^0.28.8
  kysely-postgres-js: ^3.0.0
  postgres: ^3.4.7
  turbo: ^2.6.0
  typescript: ^5.9.3
  vitest: ^4.0.8
