packages:
  - packages/*

catalog:
  '@biomejs/biome': 2.4.9
  '@types/node': ^24.10.0
  '@vitest/coverage-v8': ^4.1.2
  kysely: ^0.28.14
  kysely-postgres-js: ^3.0.0
  postgres: ^3.4.7
  turbo: ^2.8.21
  typescript: ^6.0.2
  vitest: ^4.1.2
